/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.VIEW;

import br.com.DAO.LabDAO;
import br.com.DTO.LabDTO;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno.saolucas
 */
public class InternalFrameLaboratorio extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalFrameLaboratorio
     */
    public InternalFrameLaboratorio() {
        initComponents();

        LabDAO lDAO = new LabDAO();
        lDAO.pesquisaAuto();
    }

    public void setFields() {
        int setar = tblLaboratorio.getSelectedRow();
        txtID.setText(tblLaboratorio.getModel().getValueAt(setar, 0).toString());
        txtNomeLab.setText(tblLaboratorio.getModel().getValueAt(setar, 1).toString());
        txtQuantMaquinas.setText(tblLaboratorio.getModel().getValueAt(setar, 2).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDeletar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtQuantMaquinas = new javax.swing.JTextField();
        txtNomeLab = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLaboratorio = new javax.swing.JTable();
        txtPesquisa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        txtID = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/deletar_icone.png"))); // NOI18N
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 105, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 11, -1, -1));

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/limpar_icone.png"))); // NOI18N
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 105, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 61, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quantidade de Máquinas:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 102, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 65)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lab_title.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 67, -1, -1));

        txtQuantMaquinas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtQuantMaquinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 99, 145, -1));

        txtNomeLab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNomeLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeLabActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomeLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 58, 250, -1));

        tblLaboratorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Quantidade de Máquinas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLaboratorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLaboratorioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLaboratorio);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 215, 900, 315));

        txtPesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });
        getContentPane().add(txtPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 165, 253, 32));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar_icone.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 165, -1, -1));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar_icone.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 58, -1, -1));

        txtID.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtID.setForeground(new java.awt.Color(255, 255, 255));
        txtID.setText("...");
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 11, -1, -1));

        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cadastrar_icone.png"))); // NOI18N
        btnCadastrar.setToolTipText("");
        btnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 58, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg_lab.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeLabActionPerformed

    }//GEN-LAST:event_txtNomeLabActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if (txtNomeLab.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ERRO: Preencha o campo Nome");
        } else if (txtQuantMaquinas.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ERRO: Preencha o campo Quantidade de Máquinas");
        } else {
            // Captura
            String nome_lab = txtNomeLab.getText();
            int quant_maq = Integer.parseInt(txtQuantMaquinas.getText());

            // Transferência
            LabDTO objLabDTO = new LabDTO();
            objLabDTO.setNome_lab(nome_lab);
            objLabDTO.setQuant_maquinas(quant_maq);

            // Instância
            LabDAO objLabDAO = new LabDAO();
            objLabDAO.registrarLaboratorio(objLabDTO);
            objLabDAO.limpar();
            objLabDAO.pesquisaAuto();
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        if (txtNomeLab.getText().isEmpty() && txtQuantMaquinas.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ERRO: Opa! Não há nada a ser limpado.");
        } else {
            // Instância
            LabDAO objLabDAO = new LabDAO();
            objLabDAO.limpar();
        }
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (txtID.getText().equals("...")) {
            JOptionPane.showMessageDialog(null, "ERRO: Opa! Selecione um Laboratório da Tabela de Pesquisa para poder editá-lo!");
        } else {
            // Captura
            String id_lab = txtID.getText();
            String nome_lab = txtNomeLab.getText();
            int quant_maq = Integer.parseInt(txtQuantMaquinas.getText());

            // Transferência
            LabDTO objLabDTO = new LabDTO();
            objLabDTO.setId_lab(Integer.parseInt(id_lab));
            objLabDTO.setNome_lab(nome_lab);
            objLabDTO.setQuant_maquinas(quant_maq);

            // Instância
            LabDAO objLabDAO = new LabDAO();
            objLabDAO.editar(objLabDTO);
            objLabDAO.pesquisaAuto();
            objLabDAO.limpar();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        if (txtID.getText().equals("...")) {
            JOptionPane.showMessageDialog(null, "ERRO: Opa! Selecione um Laboratório da Tabela de Pesquisa para poder deletá-lo.");
        } else if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja deletar este laboratório?",
                "Deletar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

            String id_usuario = txtID.getText();

            LabDTO objLabDTO = new LabDTO();
            objLabDTO.setId_lab(Integer.parseInt(id_usuario));

            LabDAO objLabDAO = new LabDAO();
            objLabDAO.apagar(objLabDTO);
            objLabDAO.pesquisaAuto();
            objLabDAO.limpar();
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void tblLaboratorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLaboratorioMouseClicked
        setFields();
    }//GEN-LAST:event_tblLaboratorioMouseClicked

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        LabDAO lDAO = new LabDAO();
        lDAO.pesquisa();
        
    }//GEN-LAST:event_txtPesquisaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblLaboratorio;
    private javax.swing.JLabel txtID;
    public static javax.swing.JTextField txtNomeLab;
    public static javax.swing.JTextField txtPesquisa;
    public static javax.swing.JTextField txtQuantMaquinas;
    // End of variables declaration//GEN-END:variables
}
